/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author noemi
 */
public class FenetreConnexion extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rset;
     
    
    public void connexionAdmin(){
        String id = jtf_id.getText();
        String mdp = jpf_mdp.getText();
        
        Connection conIS;
        Statement stmIS;
        ResultSet resIS;
        int existe = 0;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conIS = DriverManager.getConnection("jdbc:oracle:thin:@iutdoua-ora.univ-lyon1.fr:1521:cdb1","p2003225","564077");
            String query = "SELECT count(*) as existe FROM P2003225.CPOA_ADMIN where EMAIL_ADMIN = '"+id+"' AND MDP_ADMIN = '"+mdp+"'";
            stmIS = conIS.createStatement();
            resIS = stmIS.executeQuery(query);
            while (resIS.next()){
                existe = resIS.getInt("existe");
            }
            stmIS.execute(query);
            conIS.close();
            stmIS.close();
            resIS.close();
        } catch (Exception e) {
            if (e.getMessage() != null) {JOptionPane.showMessageDialog(null,"erreur recherche de la personne " + e.getMessage());}
        }
        
        if (existe == 0) {
            JOptionPane.showMessageDialog(null,"erreur dans le mot de passe ou le login");
        }else{
            JOptionPane.showMessageDialog(null,"vous êtes désormais connecté");
            FenetreProduits produit = new FenetreProduits();
            produit.setVisible(true);

            FenetreCategories categorie = new FenetreCategories();
            categorie.setVisible(true);
   
        }
        
    }
    
    /**
     * Creates new form Fenetre
     */
    public FenetreConnexion() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_connexion = new javax.swing.JPanel();
        jtf_id = new javax.swing.JTextField();
        jpf_mdp = new javax.swing.JPasswordField();
        jl_id = new javax.swing.JLabel();
        jl_mdp = new javax.swing.JLabel();
        jb_connexion = new javax.swing.JButton();
        jp_entete = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Jardin d'Enfants");
        setSize(new java.awt.Dimension(800, 600));

        jtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idActionPerformed(evt);
            }
        });

        jpf_mdp.setToolTipText("");
        jpf_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpf_mdpActionPerformed(evt);
            }
        });

        jl_id.setText("identifiant");

        jl_mdp.setText("mot de passe");

        jb_connexion.setBackground(new java.awt.Color(153, 0, 0));
        jb_connexion.setForeground(new java.awt.Color(255, 255, 255));
        jb_connexion.setText("se connecter");
        jb_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_connexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_connexionLayout = new javax.swing.GroupLayout(jp_connexion);
        jp_connexion.setLayout(jp_connexionLayout);
        jp_connexionLayout.setHorizontalGroup(
            jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_connexionLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_connexionLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jb_connexion))
                    .addGroup(jp_connexionLayout.createSequentialGroup()
                        .addGroup(jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_mdp)
                            .addComponent(jl_id))
                        .addGap(18, 18, 18)
                        .addGroup(jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_id)
                            .addComponent(jpf_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_connexionLayout.setVerticalGroup(
            jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_connexionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_id)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_mdp)
                    .addComponent(jpf_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jb_connexion)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jp_entete.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONNEXION");

        javax.swing.GroupLayout jp_enteteLayout = new javax.swing.GroupLayout(jp_entete);
        jp_entete.setLayout(jp_enteteLayout);
        jp_enteteLayout.setHorizontalGroup(
            jp_enteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        jp_enteteLayout.setVerticalGroup(
            jp_enteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_enteteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_entete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_connexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_entete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_connexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpf_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_mdpActionPerformed

    private void jb_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_connexionActionPerformed
        connexionAdmin();
    }//GEN-LAST:event_jb_connexionActionPerformed

    private void jtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jb_connexion;
    private javax.swing.JLabel jl_id;
    private javax.swing.JLabel jl_mdp;
    private javax.swing.JPanel jp_connexion;
    private javax.swing.JPanel jp_entete;
    private javax.swing.JPasswordField jpf_mdp;
    private javax.swing.JTextField jtf_id;
    // End of variables declaration//GEN-END:variables
}
